### ISSUE TITLE
MissingMethodException for AVX on windows

### ISSUE THREAD

**Issue by ycrumeyrolle** [gfoidl/Base64#15]
Hi, 

Just tried the encoder on Windows, but I have this error either when running tests or benchmarks:
Tests: 
```
Message: System.MissingMethodException : Method not found:
System.Runtime.Intrinsics.Vector256`1<!!1>
System.Runtime.Intrinsics.X86.Avx.StaticCast(System.Runtime.Intrinsics.Vector256`1<!!0>).
```

Benchmarks:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'gfoidl.Base64.Base64Encoder' threw an exception. ---> System.MissingMethodException: Method not found: 'System.Runtime.Intrinsics.Vector256`1<SByte> System.Runtime.Intrinsics.X86.Avx.SetVector256(SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte, SByte)'.
   at gfoidl.Base64.Base64Encoder..cctor()
   --- End of inner exception stack trace ---
   at gfoidl.Base64.Base64Encoder..ctor()
   at gfoidl.Base64.Base64.get_Default() in C:\dev\git\Base64\source\gfoidl.Base64\Base64.cs:line 16
   at gfoidl.Base64.Benchmarks.Base64EncoderBenchmarks..ctor() in C:\dev\git\Base64\perf\gfoidl.Base64.Benchmarks\Base64EncoderBenchmarks.cs:line 5
   at BenchmarkDotNet.Autogenerated.Runnable_17..ctor() in C:\dev\git\Base64\perf\gfoidl.Base64.Benchmarks\bin\Release\netcoreapp3.0\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149.notcs:line 11144
   at BenchmarkDotNet.Autogenerated.Runnable_17.Run(IHost host, String benchmarkName) in C:\dev\git\Base64\perf\gfoidl.Base64.Benchmarks\bin\Release\netcoreapp3.0\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149.notcs:line 11088
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\dev\git\Base64\perf\gfoidl.Base64.Benchmarks\bin\Release\netcoreapp3.0\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149\57b5b4f8-0ef5-4b3d-9dc8-7f89889b3149.notcs:line 77
```

The donet SDK is in version 3.0.100-preview-009791.

Am I missing something?

**Comment by gfoidl** [comment]
HW intrinsics in coreclr is under development, so things may change.
Right now I'm on SDK `3.0.100-preview-009765`. You have a newer one, so I'll need to react to changes made in coreclr.

Thanks for the report!

**Comment by gfoidl** [comment]
It seems like SDK `3.0.100-preview-009791` somehow doesn't support AVX / AVX2.
In coreclr I couldn't find any issue / change that indicates this. Only found https://github.com/dotnet/coreclr/issues/21174, but this seems rather unrelated to this issue, escpecially since this happens also on windows.
When the next SDK-preview shows the same issue, I'm going to report this in coreclr.

If you want to try with SDK `3.0.100-preview-009765` you can download it via
```bash
curl -o dotnet-install.sh https://dot.net/v1/dotnet-install.sh
chmod u+x ./dotnet-install.sh
./dotnet-install.sh -v 3.0.100-preview-009765
```

> running ... benchmarks

As this repo is WIP please keep in mind that #13 is still in progress.

**Comment by gfoidl** [comment]
@ycrumeyrolle FYI the HW-api have stabilized and this is fixed now. I'll release a new preview-package in the next days.
